title: phoolish philomath
paginate:	2 # The number of posts to show per page on your homepage
baseurl: ''
name: "Phoolish Philomath"
markdown: kramdown
mathjax: true
permalink: none
excerpt_separator: <!--more-->
kramdown:
  parse_block_html: true
gems:
  - jekyll-paginate
